"""create accounts table

Revision ID: 7bcb7ed01a71
Revises: 
Create Date: 2026-04-30 20:13:12.544739

"""
from collections.abc import Sequence

import sqlalchemy as sa

import app.db.encryption  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bcb7ed01a71'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wechat_appid', sa.String(length=100), nullable=False),
    sa.Column('wechat_secret', app.db.encryption.EncryptedString(length=2048), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title_prompt', sa.Text(), nullable=False),
    sa.Column('content_prompt', sa.Text(), nullable=False),
    sa.Column('style_desc', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
