"""create drafts and review_reports tables

Revision ID: 9f8cce7a7188
Revises: fe4a44d5cacf
Create Date: 2026-05-01 16:53:48.714808

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f8cce7a7188'
down_revision: str | Sequence[str] | None = 'fe4a44d5cacf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('library_item_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('cover_image_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reviewing', 'reviewed', 'published_to_wechat', 'failed', name='draftstatus'), nullable=False),
    sa.Column('review_report_id', sa.UUID(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('wechat_media_id', sa.String(length=200), nullable=True),
    sa.Column('wechat_pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_drafts_account_id_accounts')),
    sa.ForeignKeyConstraint(['library_item_id'], ['library_items.id'], name=op.f('fk_drafts_library_item_id_library_items')),
    sa.ForeignKeyConstraint(['review_report_id'], ['review_reports.id'], name='fk_drafts_review_report', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts'))
    )
    op.create_table('review_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('compliance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('originality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clickbait', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_review_reports_draft_id_drafts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_reports')
    op.drop_table('drafts')
    # ### end Alembic commands ###
