"""create tasks table

Revision ID: c5223e39a86f
Revises: 7bcb7ed01a71
Create Date: 2026-04-30 23:13:02.448952

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5223e39a86f'
down_revision: str | Sequence[str] | None = '7bcb7ed01a71'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('crawl', 'rewrite', 'review', 'publish', name='taskkind'), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
