"""create images table

Revision ID: d04b636b2aab
Revises: 9f8cce7a7188
Create Date: 2026-05-01 17:33:13.638430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04b636b2aab'
down_revision: Union[str, Sequence[str], None] = '9f8cce7a7188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('wechat_media_id', sa.String(length=200), nullable=True),
    sa.Column('wechat_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloaded', 'uploaded', 'replaced', 'removed', 'failed', name='imagestatus'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('error_msg', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], name=op.f('fk_images_draft_id_drafts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_foreign_key('fk_drafts_review_report', 'drafts', 'review_reports', ['review_report_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_drafts_review_report', 'drafts', type_='foreignkey')
    op.drop_table('images')
    # ### end Alembic commands ###
