"""create library_items table

Revision ID: d0f2ca49469f
Revises: c5223e39a86f
Create Date: 2026-04-30 23:16:09.253955

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd0f2ca49469f'
down_revision: str | Sequence[str] | None = 'c5223e39a86f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('original_author', sa.String(length=200), nullable=True),
    sa.Column('original_content_html', sa.Text(), nullable=True),
    sa.Column('original_content_text', sa.Text(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='librarystatus'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_library_items')),
    sa.UniqueConstraint('source_url', name=op.f('uq_library_items_source_url'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_items')
    # ### end Alembic commands ###
