"""create ai_providers, role_bindings, ai_usage tables

Revision ID: fe4a44d5cacf
Revises: d0f2ca49469f
Create Date: 2026-05-01 16:46:20.190154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.encryption  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'fe4a44d5cacf'
down_revision: Union[str, Sequence[str], None] = 'd0f2ca49469f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', app.db.encryption.EncryptedString(length=4096), nullable=False),
    sa.Column('models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_ai_providers_name'))
    )
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_usage_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    op.create_table('role_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('writer', 'reviewer', 'lite', name='role'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_role_bindings_provider_id_ai_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_bindings')),
    sa.UniqueConstraint('role', name=op.f('uq_role_bindings_role'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_bindings')
    op.drop_table('ai_usage')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
